Fix generation if jenkins job does not have the "disabled" property
Older Jenkins versions do not have the "disabled" key when getting a
job. So check for it first before using it. This fixes:

KeyError: 'disabled'